---
- hosts: vbox
  become: true
  become_user: root
  remote_user: ansibleadm
  tasks:
  - name: hostname is set
    hostname:
      name: "{{ inventory_hostname }}"
    when: not inventory_hostname|trim is match('(\d{1,3}\.){3}\d{1,3}')

  - name: Ensure hostname is in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^{{ ansible_default_ipv4.address }}.+$"
      line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

  # hosts file are the same for all
  - name: Template a file to /etc/hosts
    ansible.builtin.template:
      src: templates/hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: u=rw,g=r,o=r
